// <auto-generated />
using System;
using API.Dal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Dal.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260612164722_updateDb")]
    partial class updateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Dal.Model.IdempotencyRecordsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("idempotencyKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("paymentModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("paymentResponseBodyId")
                        .HasColumnType("int");

                    b.Property<string>("requesHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("idempotencyKey")
                        .IsUnique();

                    b.HasIndex("paymentModelId");

                    b.HasIndex("paymentResponseBodyId");

                    b.ToTable("idempotencyRecords", (string)null);
                });

            modelBuilder.Entity("API.Dal.Model.PaymentModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("orderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("API.Dal.Model.PaymentResponseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("paymentRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentResponseModel");
                });

            modelBuilder.Entity("API.Dal.Model.IdempotencyRecordsModel", b =>
                {
                    b.HasOne("API.Dal.Model.PaymentModel", "paymentModel")
                        .WithMany()
                        .HasForeignKey("paymentModelId");

                    b.HasOne("API.Dal.Model.PaymentResponseModel", "paymentResponseBody")
                        .WithMany()
                        .HasForeignKey("paymentResponseBodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paymentModel");

                    b.Navigation("paymentResponseBody");
                });
#pragma warning restore 612, 618
        }
    }
}
